### ISSUE TITLE
Create sitemap for proposed structure

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#124]

**Comment by smit1678** [comment]
From @brendangatens, site map based on a restructure to help emphasize what is HOT, where is community and work being done, how to get involved, and a full community section. Colors match type of content across pages. 

[Larger view along with wireframes here.](https://marvelapp.com/2g8782a/screen/36545094)

![sitemap](https://user-images.githubusercontent.com/796838/34272769-356ba0ba-e657-11e7-8e2d-249ea766f6d3.png)

**Comment by bgirardot** [comment]
I do not see job openings listed anywhere.

**Comment by pantierra** [comment]
It is clearly a new direction and I have to say that I generally like the approach. However there are a few things that we might want to think about and whether we want or not to drop them.

The current website links projects with news with type of project (disaster mapping, community or technical). This allowed each project to have their own kind of landing page. For example: 

https://www.hotosm.org/projects/mapping_financial_inclusion_in_uganda

or users to get an overview of projects of a certain type: https://www.hotosm.org/projects/community

The basic motivation was to give projects in the field a flexible way of blogging while contributing to all HOT news, but also getting a local, project specific link to give people that are firstly more interested in the project itself rather than in HOT as a whole.

We also had a connection of user profiles and working groups, as well as user profiles with board, staff or membership list... But I guess those were not very successful. Manually maintained lists seem to be easier to handle in the HOT website workflow.

**Comment by smit1678** [comment]
> The current website links projects with news with type of project (disaster mapping, community or technical). This allowed each project to have their own kind of landing page.

@xamanu Good question, but yes, this is still the plan. Based on the current approach, we're not only going to have project grouping (I think we still need to get our terminology right) pages, but also individual project pages. These weren't mocked up yet in wireframe yet, but the you can see the Country view here: https://marvelapp.com/2g8782a/screen/36545091. Which also gives the opportunity for a primary contact within that community. 

> We also had a connection of user profiles and working groups, as well as user profiles with board, staff or membership list... But I guess those were not very successful. Manually maintained lists seem to be easier to handle in the HOT website workflow.

Agreed. I mentioned this in #127 but yeah, we still need to sort out how we'll maintain them. I think based on our previous discussions in the working group that we'll still have this functionality - member profiles, staff, and board pages. We're leaning towards Jekyll at the moment, and so anyone can still keep their profile up to date but we'll also make it easier for the website to just update manually to keep everyone's profile fresh.

**Comment by smit1678** [comment]
> I do not see job openings listed anywhere.

@bgirardot Good point. I think we've been tackling the larger views and pages first but this will for sure still be a part of the structure.

**Comment by smit1678** [comment]
Closing this out as we've implemented the first version of the site. Open new tickets for new proposals.
