### ISSUE TITLE
Partner with Us page

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#145]
For initial version, Partner with Us page todo: 
  - Bootstrap with initially written content
  - Discuss Partners logo page from old site after new page is bootstrapped, what do we do with it?

**Comment by smit1678** [comment]
@brendangatens We have all the pieces in place now, correct?

If so, next action is to review and update the draft content.

**Comment by brendangatens** [comment]
Yes. At the moment though this is just a standard text page using text from the content doc. Interested to see if there are any further requirements. http://www-dev.hotosm.org/partners/

**Comment by Dragneel7** [comment]
Hi @brendangatens @smit1678, the "Partner with us" link onclick leads to "http://www-dev.hotosm.org/partners/partnerships@hotosm.org". Correct me if I am wrong, I believe that that it should have opened up the mail manager to mail-to :  "partnerships@hotosm.org".
This is because the href tag for the link is : `{{ page['Partner Contact']['Contact Email'] }}`
Instead it should be : `mailto:{{ page['Partner Contact']['Contact Email'] }}`.

**Comment by smit1678** [comment]
We've updated the layout and fixed the mail to link. Next action here is to finalize content.

**Comment by smit1678** [comment]
This has been updated. @RebeccaFirthy let's pick which projects show up on the sections.
