### ISSUE TITLE
Add flag to feature project on Our Work page

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#155]
@brendangatens @RebeccaFirthy Did we settle on adding a way to highlight projects on the Our Work page? 

Should we consider adding a metadata flag to enable this?

**Comment by brendangatens** [comment]
Currently, it's set up so that position in the CMS determines whether or not a project is highlighted (In Siteleaf, it's easy to drag and drop in the list of projects to re-order).

<img width="1071" alt="screenshot 2018-03-15 09 03 56" src="https://user-images.githubusercontent.com/1270986/37453536-d679b536-282f-11e8-8330-4ca64447e59d.png">


Highlight treatment will also depend on which project index is being viewed (meaning the _Our Work_, _Impact Area_ and _Country_ pages). The top 5 projects will appear as highlighted on the _Our Work_ page, whereas the top 3 projects labeled as _Water & Sanitation_ will be highlighted on the page for that impact area. Same for countries.

Using position will ensure that each Country has a highlighted project attached to it. We may not want a project (_Ecuador Earthquake_ as an example) highlighted on the Our Work page. However, We may want it treated as a highlight on the Ecuador page. So if _Ecuador Earthquake_ is positioned—in the full index of projects—higher than any other Ecuador project, it will be treated as a highlight when on the Ecuador page.
