### ISSUE TITLE
Project page: add link to project type tag

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#193]
![image](https://user-images.githubusercontent.com/796838/39189265-7e59355a-47da-11e8-9481-2a8b00de4b55.png)

**Comment by brendangatens** [comment]
Rather than being an _Impact Area_ tag with a link, this is another spot where my intention was to display HOT's involvement (`HOT Program` or `Community-led`). Previously, I added the tag to the project thumbnails, but it looks like I didn't do so here. Project _Impact Areas_ are already displayed and linked in the right-hand column on these pages.

I've just added a fix for this: https://github.com/hotosm/hotosm-website/commit/8fe01d12e9d6ce5a91b97612fd98bbda6e67a584
