### ISSUE TITLE
Landing page viz changes

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/hotosm-website#292]
With reference to https://github.com/hotosm/hotosm-website/issues/128#issuecomment-392342072 two map related tasks can be outlined for landing page:

- pulsating dots
- heat map of all TM projects

### Pulsating dots
🎯 Objective: to give a sense of active areas

- a separate json of TM projects active in the last 24 hours will be generated using [stats-collector](https://github.com/hotosm/stats-collector/). 
-This json file called `lastActive.json` is overlaid on the map as a `circle` layer
- Hovering over the circles gives a pop-up with a link to tasking manager page
- On a given day, there can be n(n >1) active projects

### Heat map
🎯 Objective: provide an overview of density of projects across countries

- This has all the projects pulled from the tasking manager API as point data
- There's no clustering here. End user has to zoom in to see project points & related pop-up with TM links
- Related posts from Mapbox: [Example](https://www.mapbox.com/mapbox-gl-js/example/heatmap-layer/), [Blogpost](https://blog.mapbox.com/introducing-heatmaps-in-mapbox-gl-js-71355ada9e6c)

cc @brendangatens @smit1678

**Comment by ramyaragupathy** [comment]
@brendangatens - You can use this [allProjects.json](https://gist.github.com/ramyaragupathy/10eb71ea1095ae7caf60c23cee437f1f) for heatmap testing.
For pulsating points, here's a [codepen](https://codepen.io/ramyaragupathy/pen/qKrYLJ) based on prototype example.

**Comment by brendangatens** [comment]
One thing I don’t want to complicate, is using the map as a way to navigate to a country page. I wonder if we can use tabs—as you’ve suggested—but with the two options being **Country view** and **Project view**.

![country-view](https://user-images.githubusercontent.com/1270986/42211009-556c50e4-7eaa-11e8-8338-68eedba89af7.png)


**Country view** would work in a similar manner to what we already have, but with the addition of a marker for each country (which should help highlight smaller countries), the pulsating dots (to highlight countries with active projects) and an updated key which should help communicate that the markers—in this view at least—are for countries, and not specific projects.

**Project view** would incorporate a way to display the density of projects, though I wonder if we could cluster projects in circles (with their size determined by the number of projects in the area) rather than a heatmap. 

Not sure if others feel the same, but to me, a heatmap has negative connotations; almost as if we’re displaying the spread of a disease, or crime data, rather than the locations in which HOT is making a positive impact.

Using circles rather than a heat map opens up the opportunity to use color for another dimension, project age or active/completed projects. 

<img width="984" alt="screenshot 2018-07-03 09 01 57" src="https://user-images.githubusercontent.com/1270986/42211051-7636ae46-7eaa-11e8-9c90-6d798f0c49d1.png">

The above example has larger circles representing groups of projects at higher zoom levels. The last screen shows the clusters reaching a break point where the groups dissipate into individual project markers.

**Comment by ramyaragupathy** [comment]
This design with tab view looks great @brendangatens. I need to modify the last active project generation a bit. Could you please share the country centroid file that you're using for the map?  Accordingly I can modify the data fetch for the landing page.
Also agree with your point on heat map, my overall idea behind the heatmap was to keep it different from the map view in tasking manager page
![image](https://user-images.githubusercontent.com/12103383/42365457-28ffafaa-811c-11e8-8796-d107601a49ee.png)

The design you've posted has circles + opacity overlay that communicates the density of projects across countries. This looks good to me. 

cc @smit1678

**Comment by ramyaragupathy** [comment]
Live through https://github.com/hotosm/hotosm-website/pull/346
