### ISSUE TITLE
Fix rss/atom feed to hotosm.org/updates/

### ISSUE THREAD

**Issue by tordans** [hotosm/hotosm-website#338]
*Update:* Apparently there was a feed at https://www.hotosm.org/feed/rss2 which does not work anymore. Ideally the old URLs would continue working.

---

The blog at https://www.hotosm.org/updates/ does not have an RSS feed which makes the email newsletter the only feasible way to get informed about updates.

Please add an rss feed so I can subscribe to updates.

```
<link rel="alternate" type="application/rss+xml" 
  title="Humanitarian OpenStreetMap Team | News" 
  href="/updates.rss" />
```

**Comment by smit1678** [comment]
👍 good call @tordans, let's get the RSS back online

**Comment by smit1678** [comment]
Finally dug into this and realized that we had already set up `jekyll-feed` here: https://github.com/hotosm/hotosm-website/blob/gh-pages/_config.yml#L147. We are generating a `feed.xml` at: https://www.hotosm.org/feed.xml. 

> The blog at https://www.hotosm.org/updates/ does not have an RSS feed which makes the email newsletter the only feasible way to get informed about updates.

@tordans any reason why we would want to put the feed under `/updates` instead of at the root level? Also is the feed.xml not working for your reader?

**Comment by smit1678** [comment]
Update: I think this will help with discoverability: https://github.com/hotosm/hotosm-website/pull/350

**Comment by russdeffner** [comment]
Any update to this? I realize I am totally not paying attention to our blog without the RSS feed.

**Comment by smit1678** [comment]
@russdeffner Thanks for the ping, yes this was fixed but we didn't close it out. The RSS feed can be found here directly: https://www.hotosm.org/feed.xml
