### ISSUE TITLE
Add zoom or pan to next feature on project maps

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-website#419]
Problem: A number of projects have multiple implementation areas. For example, Inaware project is implemented across three cities in Indonesia: https://www.hotosm.org/projects/disaster-early-warning-and-capacity-building-inaware. The map loads zoomed in on the first feature, which is helpful for better map views on global projects, but a user doesn't know that there are more features to look at. 

Potential solution: If there are more than one feature, add a zoom to next area button on map. 

<img width="1387" alt="Humanitarian OpenStreetMap Team | Modelling Exposure Through Earth Observation Routines: METEOR 2019-03-12 10-16-47" src="https://user-images.githubusercontent.com/796838/54172392-72a72400-44b0-11e9-811d-f3ec3dac14d7.png">

other suggestions @ramyaragupathy?

**Comment by ramyaragupathy** [comment]
Thanks for ticketing this @smit1678! We need to handle multiple geographies as we extend it for more projects. `Zoom to next area` is a good plan. However, doesn't provide a high-level view of all areas covered. I propose using something like this example https://docs.mapbox.com/mapbox-gl-js/example/scroll-fly-to/. 

![flyable](https://user-images.githubusercontent.com/12103383/54180857-b440ca80-44c2-11e9-9f9c-dea3ea8ac736.gif)

We will have a `View all areas` button  at the bottom right corner (instead of `Zoom to next area`). Upon clicking let's have a sidebar on the left with a name list of all areas. User gets to see each area by clicking on it. We could also include a collapsible dropdown sort of fucnitonality next to each name, where it gives a summary of projects.

**Comment by katia-utochkina** [comment]
Hi @smit1678 and @ramyaragupathy, I would love to contribute. Could I have the issue assigned to me?

**Comment by ramyaragupathy** [comment]
Sure you're free to pick this for work @katia-utochkina. Let me know if you have questions.

**Comment by Muskan284** [comment]
@ramyaragupathy ,can i work on this issue?

**Comment by bismitaguha** [comment]
Hi @smit1678 and @ramyaragupathy , I would like to work on this feature.

**Comment by ramyaragupathy** [comment]
Fixed through https://github.com/hotosm/hotosm-website/pull/516. Thanks for the fix @katia-utochkina 🎉
