### ISSUE TITLE
Generic HOT toolbar

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/hotosm-website#77]
@xamanu Just wanted to add this suggestion made by Pierre Beland during the Technical WG meeting before we forget.

He mentioned that it was discussed a while ago that a bar should be added to the top of the HOT website that links to the Tasking Manager and the Export Tool. This can also be expanded if and when we develop any other tools.

I should also note that I have taken aspects of the HOT website and the Tasking Manager interface for the redesign of the Export Tool, so that they are consistent and representative of HOT, as well as making all our online sites familiar and easier to navigate for our users.

**Comment by xamanu** [comment]
Thank you @mataharimhairi 
This consistent HOT bar is something we should consider in the redesign. 
For the HOT export tool @KatjaUlbert can actually provide you with good practices and the right colour so we can start using as a first step, at least the same red and grey tones.

**Comment by KatjaUlbert** [comment]
@mataharimhairi  hot-osm red is #D73F3F grey is #808080

**Comment by KatjaUlbert** [comment]
Remarks/suggestions: The logo should be completely in the red bar so that the lower half doesn´t disappear. Could you change the HOT Export font in the red bar to the sans-serif? You can use the serif font in red for the HOT Export headline instead. I saw that you used color gradients and/or shadows, they´re not used on hotosm.org, so I think you should remove them for consistency reasons.

If you like I can create an Export version of the HOT Logo (Export or Export Tool standing next to the logo)

**Comment by russdeffner** [comment]
I think it's great to push export, TM and LearnOSM to even better visibility on the main website; but I would also say that maybe whatever/wherever we do it, first have them land on the project page? I think some people who would come to the site would also want the information contained there (dates, blogs, eventually the project leads/contacts) rather than just getting directed directly to the project page (i.e. it may be confusing to tell people - go to website for updates/contacts/etc. and the first thing they see sends them to the tool itself).

**Comment by mataharimhairi** [comment]
@KatjaUlbert This is great. Thank you. I am actually going to put you in touch with Arushi - the Outreachy intern who is working on the HOT Export Tool mockup, so that you might be able to assist her with things like the logo and colour scheme if you don't mind :)

**Comment by xamanu** [comment]
Yes, @russdeffner, I agree that such  generic HOT toolbar can be confusing to people who don't know what is behind the different tools and jump from one site to another. I think it could be a small gear (looking like the hot logo), which can be used by people who know that they want to jump from one place to another, but is decent enough to be ignored by new people who are trying to get familiar with HOT and it's tools.

**Comment by KatjaUlbert** [comment]
links to the export tool and tasking manager will be on the project and get involved > mapping page. Close issue?

**Comment by xamanu** [comment]
Yes, closing here.
