### ISSUE TITLE
Map of HOT members

### ISSUE THREAD

**Issue by cgiovando** [hotosm/hotosm-website#94]
We make and love maps, but we don't have a map showing where HOT members are. Would be nice to show a simple political map with major cities and approximate location pins of each member. This could be sourced from details that members fill in their Drupal/OSM user profiles. Is that realistic? Would the Leaflet component work for this? https://www.drupal.org/project/leaflet

**Comment by mellig** [comment]
@xamanu Would this be technically complex to create? If possible but time consuming we could add it to a wish list for further down the road, instead of including it as a new visual/content piece in the redesign.

**Comment by xamanu** [comment]
@mellig It is indeed a nice idea, but not very necessary. It is not very complex to implement, it is rather complex to get (all) people to login and pin themselves to the map. And even more difficult having them maintaining their location information up-to-date.

We also have a country field on user profiles on the website. So, instead of using a map with pins we could just show coutries and numbers of people in it. But this, yes, would be more work and I have no idea if it is worth the effort.

**Comment by TylerRadford** [comment]
I like the idea and agree we don't have great data on the locations of members. I do think we need more maps! I'm going to open another issue related to a map of projects worldwide.

**Comment by KatjaUlbert** [comment]
not yet implemented.

**Comment by xamanu** [comment]
Closing here.
